name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  # Job build backend
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Spring Boot
        working-directory: ./backend/eventapp-backend
        run: |
          ./mvnw clean package -DskipTests

  # Job build frontend, chạy sau backend
  build-frontend:
    needs: build-backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run lint
        working-directory: ./frontend
        run: npm run lint

      - name: Build Next.js
        working-directory: ./frontend
        run: npm run build
